export const ingredientList = [   
    "Grapefruit Juice",
    "Mint Simple",
    "Rosemary Simple",
    "Coconut Milk",
    "Iced Tea",
    "Apple Cider",
    "Cranberry Juice",
    "Grape Juice",
    "Orange Juice",
    "Pickle Juice",
    "Pineapple Juice",
    "Anchovy Juice",
    "Sriracha",
    "Olive Juice",
    "Lime Juice",
    "Lemon Juice",
    "Simple Syrup",
    "Honey",
    "Peach Juice",
    "Mango Juice",
    "Tomato Juice",
    "Garlic Juice",
    "Fish Sauce",
    "Beet Juice",
    "Cream",
  ]
  
  export const alcoholList = [
      "Vodka",
      "Whiskey",
      "Gin",
      "Jägermeister",
      "Tequila",
      "Wine",
      "IPA",
      "Chartreuse",
  ]
  
  export const nameList = [
      "The Abomination",
      "The Taste is Familiar...",
      "I Don't Think I'm Thirsty Anymore",
      "Sweet/Sour/I Don't Know",
      "Unelevated and Sedated",
      "'This is Great' *tosses drink",
      "Hair of the Dog?",
  ]
  
  
  
  export const vodkaList = [ //for vodka button
    "Lemon Juice",
    "Lime Juice",
    "Orange Juice",
    "Cranberry Juice",
    "Pineapple Juice",
    "Grapefruit Juice",
    "Simple Syrup",
    "Mint Leaves",
    "Fresh Basil",
    "Cucumber",
    "Ginger Beer",
    "Triple Sec",
    "Peach Schnapps",
    "Fresh Berries",
    "Coconut Water",
    "Fresh Lemonade",
    "Fresh Limeade",
  
  ]
  
  export const whiskeyList = [ //for whiskey button
    "Sweet Vermouth",
    "Dry Vermouth",
    "Campari",
    "Amaro",
    "Cointreau",
    "Grand Marnier",
    "Triple Sec",
    "Absinthe",
    "Bénédictine",
    "Chartreuse",
    "Fernet-Branca",
    "Drambuie",
    "Sambuca",
    "Peach Schnapps",
    "Apple Schnapps",
    "Cherry Heering",
    "Luxardo Maraschino",
    "Angostura Bitters",
    "Peychaud's Bitters",
    "Orange Bitters",
  ]
  
  export const tequilaList = [ // for tequila button
  
    "Lime Juice",
    "Lemon Juice",
    "Orange Juice",
    "Grapefruit Juice",
    "Pineapple Juice",
    "Coconut Water",
    "Ginger Beer",
    "Ginger Ale",
    "Agave Syrup",
    "Simple Syrup",
    "Honey",
    "Mint Leaves",
    "Fresh Basil",
    "Cucumber Slices",
    "Watermelon Juice",
    "Mango Juice",
    "Passion Fruit Juice",
    "Fresh Lemonade",
    "Fresh Limeade",
    "Angostura Bitters", 
    "Orange Bitters",
      
  ]
  
  export const ginList = [ //for gin button
  
    "Dry Vermouth",
    "Sweet Vermouth",
    "Campari",
    "Aperol",
    "St-Germain",
    "Cointreau",
    "Grand Marnier",
    "Triple Sec",
    "Pimm's No. 1",
    "Angostura Bitters",  
    "Orange Bitters",     
    "Lemon Juice",
    "Lime Juice",
    "Grapefruit Juice",
    "Orange Juice",
    "Elderflower Cordial",
    "Rosemary Simple Syrup",
    "Mint Simple Syrup",
    "Tonic Water",
    "Club Soda",
    "Ginger Beer",
    "Ginger Ale",
    "Cucumber Slices",
    "Fresh Basil",
    "Fresh Mint Leaves",
    "Fresh Rosemary",
  
  ]
  
  export const rumList = [ // for rum button
  
      "Triple Sec",
      "Grand Marnier",
      "Curaçao",
      "Falernum",
      "Campari",
      "Apricot Brandy",
      "Coffee Liqueur",
      "Coconut Cream Liqueur",
      "Lime Juice",
      "Lemon Juice",
      "Pineapple Juice",
      "Orange Juice",
      "Coconut Cream",
      "Coconut Water",
      "Ginger Beer",
      "Ginger Ale",
      "Tonic Water",
      "Club Soda",
      "Mint Leaves",
      "Fresh Basil",
      "Cinnamon Sticks",
      "Simple Syrup",
      "Brown Sugar",
      "Fresh Grated Nutmeg",
      "Fresh Mango Juice",
      "Banana Puree",
  
  ]
  
  export const mocktailList = [ // for mocktail button
    "Orange Juice",
    "Lemon Juice",
    "Lime Juice",
    "Pineapple Juice",
    "Cranberry Juice",
    "Apple Juice",
    "Grape Juice",
    "Mango Juice",
    "Peach Juice",
    "Pomegranate Juice",
    "Simple Syrup",
    "Agave Syrup",
    "Honey",
    "Fresh Mint Leaves",
    "Fresh Basil",
    "Fresh Rosemary",
    "Fresh Thyme",
    "Lemon Slices",
    "Lime Slices",
    "Orange Slices",
    "Cucumber Slices",
    "Star Anise",
    "Vanilla Extract"
  ]
  